/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_gen.h"
#include<stdio.h> //printf
#include<string.h>    //memset
#include<errno.h> //errno
#include<sys/socket.h>
#include<netdb.h>
#include<ifaddrs.h>
#include<stdlib.h>
#include<unistd.h>
#include<time.h>

#include <iostream>
#include <string>

#include "client/udp_handler.h"
#include "client/obj_ptr.h"
#include "util/common_util.h"

UDPReceiver *udp_recv_obj;
CLIENT *clnt;
int clientPort;
char *clientIp;

const std::string articles[12] = { "Sports;;contents",
                                   ";Someone;UMN;contents_for_someone",
                                   "Science;Someone2;UMN;contents_for_someone2",
                                   "Science;Someone2;UMN;contents_for_someone2",
                                   "Science;;UMN;contents_for_someone2",
                                   "Science;2;UMN;contents_for_2_Science",
                                   "Business;Joe;UMN;contents_for_someone2",
                                   "Lifestyle;Someone2;UMN;contents_for_someone2_Lifestyle",
                                   "Entertainment;Someone2;UMN;contents_for_someone2_Entertainment",
                                   "Technology;Someone2;UMN;contents_for_someone2_Technology",
                                   "Politics;Someone2;UMN;contents_for_someone2_Politics",
                                   "Health;Someone2;UMN;contents_for_someone2_health"
                                 };

const std::string subscription[12]={"Sports;;",
                                   ";Someone;UMN;",
                                   "Science;Someone2;;",
                                   "Science;Someone2;UMN;",
                                   "Science;;UMN;",
                                   "Science;2;UMN;",
                                   ";Joe;UMN;",
                                   "Lifestyle;Someone2;UMN;",
                                   "Entertainment;Someone2;UMN;",
                                   "Technology;Someone2;UMN;",
                                   ";Someone2;UMN;",
                                   "Health;Someone2;UMN;"
                                 };


void interrupt_handler(int x){
	std::cout << "De-Registering "<<std::endl;
	int *result_leave;
	result_leave = leave_1(clientIp, clientPort, clnt);
    if (result_leave == (int *)NULL){
		clnt_perror (clnt, "call failed");
    }
    
    //udp_obj->deregister();
	clnt_destroy (clnt);
	exit(0);
}



	//communicate_prog_1 (host, clientIp, clientPort, publish_choice, subscribe_choice);
void
communicate_prog_1(char *host, char* clientIp, int clientPort, int publish_choice, int subscribe_choice)
{
	int  *result_1;
	char *joinserver_1_IP;
	int joinserver_1_ProgID;
	int joinserver_1_ProgVers;
	int  *result_2;
	char *leaveserver_1_IP;
	int leaveserver_1_ProgID;
	int leaveserver_1_ProgVers;
	int  *result_3;
	char *join_1_IP;
	int join_1_Port;
	int  *result_4;
	char *leave_1_IP;
	int leave_1_Port;
	int  *result_5;
	char *subscribe_1_IP;
	int subscribe_1_Port;
	char *subscribe_1_Article=(char *)malloc(sizeof(char)*120);
	int  *result_6;
	char *unsubscribe_1_IP;
	int unsubscribe_1_Port;
	char *unsubscribe_1_Article=(char *)malloc(sizeof(char)*120);
	int  *result_7;
	char *publish_1_Article=(char *)malloc(sizeof(char)*120);
	char *publish_1_IP;
	int publish_1_Port;
	int  *result_8;
	char *publishserver_1_Article=(char *)malloc(sizeof(char)*120);
	char *publishserver_1_IP;
	int publishserver_1_Port;
	int  *result_9;

#ifndef	DEBUG
	clnt = clnt_create (host, COMMUNICATE_PROG, COMMUNICATE_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    fprintf(stdout , "ClientIP: %s, Port: %d\n", clientIp, clientPort);
	result_1 = joinserver_1("s", 1, 1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    /*
	result_2 = leaveserver_1(leaveserver_1_IP, leaveserver_1_ProgID, leaveserver_1_ProgVers, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
        join_1_IP = clientIp;
        join_1_Port = clientPort;        
	result_3 = join_1(join_1_IP, join_1_Port, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
     
      /* 
        leave_1_IP = clientIp;  
        leave_1_Port = clientPort;
	result_4 = leave_1(leave_1_IP, leave_1_Port, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
 */
        subscribe_1_IP = clientIp;
        subscribe_1_Port = clientPort;
        strcpy(subscribe_1_Article, subscription[subscribe_choice].c_str());
	result_5 = subscribe_1(subscribe_1_IP, subscribe_1_Port, subscribe_1_Article, clnt);
    fprintf(stderr, "subscribe called\n");
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
        unsubscribe_1_IP = clientIp;
        unsubscribe_1_Port = clientPort;
     /*   strcpy(unsubscribe_1_Article, ";;UMN;fadflj djkahflj");
	result_6 = unsubscribe_1(unsubscribe_1_IP, unsubscribe_1_Port, unsubscribe_1_Article, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
        unsubscribe_1_IP = clientIp;
        unsubscribe_1_Port = clientPort;
        strcpy(unsubscribe_1_Article, ";;UMN;fadflj djahflj");
	result_6 = unsubscribe_1(unsubscribe_1_IP, unsubscribe_1_Port, unsubscribe_1_Article, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
*/
	sleep(2);
        strcpy(publish_1_Article, articles[publish_choice].c_str());
        publish_1_IP = clientIp;
        publish_1_Port = clientPort;
	result_7 = publish_1(publish_1_Article, publish_1_IP, publish_1_Port, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    
    int choice_1, choice_2;
    while(1){
    // TODO: INteractive Web
    fprintf(stdout, "Enter you RPC call choice:\n\t1. Publish\n\t2. Subscribe\nt\t3. Unsubscribe\n\t4. Ping\n");
    fprintf(stdout, "Enter choice: ");
    scanf("%d", &choice_1);

    switch(choice_1){
    case 1: fprintf(stdout, "Choose the article to Publish:\n\n");
            for(int i = 0 ; i < 12; ++i){
                fprintf(stdout, "\t%d. %s\n", i, articles[i].c_str());
            }
            fprintf(stdout, "Enter choice: ");
            scanf("%d", &choice_2);
            
            strcpy(publish_1_Article, articles[choice_2].c_str());
            publish_1_IP = clientIp;
            publish_1_Port = clientPort;
	        result_7 = publish_1(publish_1_Article, publish_1_IP, publish_1_Port, clnt);
	        if (result_7 == (int *) NULL) {
		        clnt_perror (clnt, "call failed");
	        }
            break;
    case 2: fprintf(stdout, "Choose the article to Subscribe:\n\n");
            for(int i = 0 ; i < 12; ++i){
                fprintf(stdout, "\t%d. %s\n", i, subscription[i].c_str());
            }
            fprintf(stdout, "Enter choice: ");
            scanf("%d", &choice_2);
            strcpy(subscribe_1_Article, subscription[choice_2].c_str());
	        result_5 = subscribe_1(subscribe_1_IP, subscribe_1_Port, subscribe_1_Article, clnt);
            fprintf(stderr, "subscribe called\n");
	        if (result_5 == (int *) NULL) {
		        clnt_perror (clnt, "call failed");
	        }
            break;

    case 3: fprintf(stdout, "Choose the article to UnSubscribe:\n\n");
            for(int i = 0 ; i < 12; ++i){
                fprintf(stdout, "\t%d. %s\n", i, subscription[i].c_str());
            }
            fprintf(stdout, "Enter choice: ");
            scanf("%d", &choice_2);
            strcpy(unsubscribe_1_Article,  subscription[choice_2].c_str());
	        result_6 = unsubscribe_1(unsubscribe_1_IP, unsubscribe_1_Port, unsubscribe_1_Article, clnt);
	        if (result_6 == (int *) NULL) {
		        clnt_perror (clnt, "call failed");
            } 
            break;
     
    case 4: 
	       result_9 = ping_1(clnt);
	       if (result_9 == (int *) NULL) {
	       	clnt_perror (clnt, "call failed");
	       } 
           else {
            fprintf(stdout, "Ping was Successful\n");
           }
           break;
    DEFAULT: fprintf(stdout, "Invalid Choice, try again or press ctrl-c to exit\n");
    };
    
    }

/*
  */      /*
	result_8 = publishserver_1(publishserver_1_Article, publishserver_1_IP, publishserver_1_Port, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = ping_1(clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
    int publish_choice, subscribe_choice; 
	signal(SIGINT, interrupt_handler);

	if (argc < 5) {
		printf ("usage: %s <server_host> <local_port> <publish> <subscription> \n", argv[0]);
		exit (1);
	}
	host = argv[1];
    publish_choice = atoi(argv[3]);
    subscribe_choice = atoi(argv[4]);
        
	clientIp = CommonUtil::getMyIpAddress();
        printf("Address: %s\n", clientIp);
        clientPort = atoi(argv[2]);
        printf("Port: %d\n", clientPort);

    udp_recv_obj = new UDPReceiver(clientPort);
        
	communicate_prog_1 (host, clientIp, clientPort, publish_choice, subscribe_choice);
    udp_recv_obj->join_all();
        free(clientIp);
        exit (0);
}
