/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <iostream>
#include "rpc_gen.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#include <csignal>

#include "util/payload_util.h"

#include "group_server/udp_intf.h"
#include "group_server/client_list.h"
#include "group_server/obj_ptr.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

UDPIntf *udp_obj;
ClientList *clients_obj;
PayLoad *pay_load_obj;

static int *
_joinserver_1 (joinserver_1_argument *argp, struct svc_req *rqstp)
{
	return (joinserver_1_svc(argp->IP, argp->ProgID, argp->ProgVers, rqstp));
}

static int *
_leaveserver_1 (leaveserver_1_argument *argp, struct svc_req *rqstp)
{
	return (leaveserver_1_svc(argp->IP, argp->ProgID, argp->ProgVers, rqstp));
}

static int *
_join_1 (join_1_argument *argp, struct svc_req *rqstp)
{
	return (join_1_svc(argp->IP, argp->Port, rqstp));
}

static int *
_leave_1 (leave_1_argument *argp, struct svc_req *rqstp)
{
	return (leave_1_svc(argp->IP, argp->Port, rqstp));
}

static int *
_subscribe_1 (subscribe_1_argument *argp, struct svc_req *rqstp)
{
	return (subscribe_1_svc(argp->IP, argp->Port, argp->Article, rqstp));
}

static int *
_unsubscribe_1 (unsubscribe_1_argument *argp, struct svc_req *rqstp)
{
	return (unsubscribe_1_svc(argp->IP, argp->Port, argp->Article, rqstp));
}

static int *
_publish_1 (publish_1_argument *argp, struct svc_req *rqstp)
{
	return (publish_1_svc(argp->Article, argp->IP, argp->Port, rqstp));
}

static int *
_publishserver_1 (publishserver_1_argument *argp, struct svc_req *rqstp)
{
	return (publishserver_1_svc(argp->Article, argp->IP, argp->Port, rqstp));
}

static int *
_ping_1 (void  *argp, struct svc_req *rqstp)
{
	return (ping_1_svc(rqstp));
}

static void
communicate_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		joinserver_1_argument joinserver_1_arg;
		leaveserver_1_argument leaveserver_1_arg;
		join_1_argument join_1_arg;
		leave_1_argument leave_1_arg;
		subscribe_1_argument subscribe_1_arg;
		unsubscribe_1_argument unsubscribe_1_arg;
		publish_1_argument publish_1_arg;
		publishserver_1_argument publishserver_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case JoinServer:
		_xdr_argument = (xdrproc_t) xdr_joinserver_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _joinserver_1;
		break;

	case LeaveServer:
		_xdr_argument = (xdrproc_t) xdr_leaveserver_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _leaveserver_1;
		break;

	case Join:
		_xdr_argument = (xdrproc_t) xdr_join_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _join_1;
		break;

	case Leave:
		_xdr_argument = (xdrproc_t) xdr_leave_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _leave_1;
		break;

	case Subscribe:
		_xdr_argument = (xdrproc_t) xdr_subscribe_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _subscribe_1;
		break;

	case Unsubscribe:
		_xdr_argument = (xdrproc_t) xdr_unsubscribe_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _unsubscribe_1;
		break;

	case Publish:
		_xdr_argument = (xdrproc_t) xdr_publish_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _publish_1;
		break;

	case PublishServer:
		_xdr_argument = (xdrproc_t) xdr_publishserver_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _publishserver_1;
		break;

	case Ping:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _ping_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

void interrupt_handler(int x){
	std::cout << "De-Registering "<<std::endl;
	udp_obj->deregister();
	exit(0);
}

int
main (int argc, char **argv)
{
    
    if (argc < 4){
        fprintf(stderr, "INCORRECT USAGE\nUSAGE:\n%s <ServerPort> <IP_RegistryServer> <Port_RegistryServer",argv[0]);
        exit(1);
    }

    char *RegistryIP; 
    uint16_t RegistryServerPort, ServerPort;

    ServerPort = atoi(argv[1]);
    RegistryIP = argv[2];
    RegistryServerPort = atoi(argv[3]);
    fprintf(stdout, "REG_IP:%s\tREG_PORT:%d\nServerPort: %d", RegistryIP, RegistryServerPort, ServerPort);

	register SVCXPRT *transp;

	pmap_unset (COMMUNICATE_PROG, COMMUNICATE_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, COMMUNICATE_PROG, COMMUNICATE_VERSION, communicate_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (COMMUNICATE_PROG, COMMUNICATE_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, COMMUNICATE_PROG, COMMUNICATE_VERSION, communicate_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (COMMUNICATE_PROG, COMMUNICATE_VERSION, tcp).");
		exit(1);
	}

    clients_obj = new ClientList();
    pay_load_obj = new PayLoad();
    udp_obj = new UDPIntf(ServerPort, inet_addr(RegistryIP), 
                            RegistryServerPort,
                            (void*)clients_obj, (void*)pay_load_obj);
	signal(SIGINT, interrupt_handler);
    uint32_t dummy_client;
    //inet_aton("128.101.37.4", (struct in_addr*)&dummy_client);
    //udp_obj->send_to_clients(dummy_client, 9211, "test 101");
//    std::cout << "Vagh Maare " << std::endl;
    int a = udp_obj->register_server();
    std::cout << "a: " << a << std::endl;
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
    udp_obj->join_all();

	exit (1);
	/* NOTREACHED */
}
