/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_code_lab.h"

int *
printmessage_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static int  result;

    FILE *f;
    f = fopen("/tmp/test", "w");
    if (f==NULL){
        result=0;
        return(&result);
    }

    fprintf(f, "%s\n", arg1);

    fclose(f);
    result = 1;

	/*
	 * insert server code here
	 */

	return &result;
}
