/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_code_lab.h"


void
messageprog_1(char *host, char *msg)
{
	CLIENT *clnt;
	int  *result_1;
	char *printmessage_1_arg1;
    
    printmessage_1_arg1 = msg;

#ifndef	DEBUG
	clnt = clnt_create (host, MESSAGEPROG, MESSAGEVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = printmessage_1(printmessage_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
    char *msg;

	if (argc < 3) {
		printf ("usage: %s <server_host> <message>\n", argv[0]);
		exit (1);
	}
	host = argv[1];
    msg = argv[2];
	messageprog_1 (host, msg);
exit (0);
}
